version: '3.8'

services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafana-external-website
    ports:
      - "3000:3000"
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-external-website-panel
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_LOG_LEVEL=debug
      - GF_LOG_MODE=console
      - GF_PLUGINS_ENABLE_ALPHA=true
    volumes:
      - grafana-data:/var/lib/grafana
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - grafana-net

networks:
  grafana-net:
    driver: bridge

volumes:
  grafana-data:
    driver: local 